# Generated by Django 5.1 on 2024-08-31 04:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpagetags_blogdetail_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True),
        ),
    ]
