# Generated by Django 5.1 on 2024-08-31 07:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1), ('corousel', 3)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.StreamBlock', [[('text', 0), ('author', 0)]], {}), 3: ('wagtail.blocks.StreamBlock', [[('image', 1), ('quotation', 2)]], {})}, null=True),
        ),
    ]
