# Generated by Django 5.1 on 2024-08-31 16:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1), ('doc', 2), ('page', 3), ('call_to_action_1', 6), ('corousel', 8)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 3: ('wagtail.blocks.PageChooserBlock', (), {}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('text', 4), ('page', 3), ('button_text', 5)]], {'label': 'CTA #1'}), 7: ('wagtail.blocks.StreamBlock', [[('text', 0), ('author', 0)]], {}), 8: ('wagtail.blocks.StreamBlock', [[('image', 1), ('quotation', 7)]], {})}, null=True),
        ),
    ]
