# Generated by Django 5.1 on 2024-09-05 14:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1), ('doc', 2), ('page', 3), ('call_to_action_1', 6), ('corousel', 8), ('info', 9), ('faq', 13)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 3: ('wagtail.blocks.PageChooserBlock', (), {}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('text', 4), ('page', 3), ('button_text', 5)]], {'label': 'CTA #1'}), 7: ('wagtail.blocks.StreamBlock', [[('text', 0), ('author', 0)]], {}), 8: ('wagtail.blocks.StreamBlock', [[('image', 1), ('quotation', 7)]], {}), 9: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'ini namanya static blocks'}), 10: ('wagtail.blocks.CharBlock', (), {}), 11: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic']}), 12: ('wagtail.blocks.StructBlock', [[('question', 10), ('answer', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'label': 'pertanyaan yg sering ditanyakan', 'max_num': 5, 'min_num': 1})}, null=True),
        ),
    ]
