# Generated by Django 5.1 on 2024-09-05 15:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1), ('doc', 2), ('page', 3), ('call_to_action_1', 6), ('corousel', 11), ('info', 12), ('faq', 13)], blank=True, block_lookup={0: ('components.blocks.TextBlock', (), {}), 1: ('components.blocks.ImageBlock', (), {}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 3: ('wagtail.blocks.PageChooserBlock', (), {}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('text', 4), ('page', 3), ('button_text', 5)]], {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 8: ('wagtail.blocks.TextBlock', (), {}), 9: ('wagtail.blocks.CharBlock', (), {}), 10: ('wagtail.blocks.StreamBlock', [[('text', 8), ('author', 9)]], {}), 11: ('wagtail.blocks.StreamBlock', [[('image', 7), ('quotation', 10)]], {}), 12: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'ini namanya static blocks'}), 13: ('components.blocks.FAQListBlock', (), {})}, null=True),
        ),
    ]
